param(
  [string]$IaCDir = "./iac/azure",
  [string]$OutputFile = "./.env.local.azure"
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path $IaCDir)) {
  Write-Error "IaC directory not found: $IaCDir"
  exit 1
}

Push-Location $IaCDir
try {
  $json = terraform output -json
  if (-not $json) {
    Write-Error "Terraform output is empty. Run 'terraform apply' first."
    exit 1
  }

  $outputs = $json | ConvertFrom-Json
  
  # Extract outputs
  $kvUri = if ($outputs.key_vault_uri) { $outputs.key_vault_uri.value } else { $null }
  $kvName = if ($outputs.key_vault_name) { $outputs.key_vault_name.value } else { $null }
  $appClientId = if ($outputs.app_client_id) { $outputs.app_client_id.value } else { $null }
  $appTenantId = if ($outputs.app_tenant_id) { $outputs.app_tenant_id.value } else { $null }
  $adminGroupId = if ($outputs.admin_group_id) { $outputs.admin_group_id.value } else { $null }
  $storageAccount = if ($outputs.storage_account_name) { $outputs.storage_account_name.value } else { $null }
  $storageContainer = if ($outputs.storage_container_name) { $outputs.storage_container_name.value } else { $null }
  $eventGridUri = if ($outputs.eventgrid_topic_endpoint) { $outputs.eventgrid_topic_endpoint.value } else { $null }
  $eventGridKey = if ($outputs.eventgrid_topic_key) { $outputs.eventgrid_topic_key.value } else { $null }
  $appInsightsKey = if ($outputs.appinsights_instrumentation_key) { $outputs.appinsights_instrumentation_key.value } else { $null }

  $content = @(
    "# Generated by scripts/generate-azure-env.ps1",
    "# Do not commit this file",
    "",
    "# Azure Application (from Terraform)",
    "GRAPH_TENANT_ID=$($appTenantId ? $appTenantId : '<REPLACE_ME>')",
    "GRAPH_CLIENT_ID=$($appClientId ? $appClientId : '<REPLACE_ME>')",
    "GRAPH_CLIENT_SECRET=<GET_FROM_KEY_VAULT>",
    "ENTRA_GROUP_ID=$($adminGroupId ? $adminGroupId : '<REPLACE_ME>')",
    "",
    "# Key Vault",
    "AZURE_KEYVAULT_URL=$($kvUri ? $kvUri : '<REPLACE_ME>')",
    "AZURE_KEYVAULT_NAME=$($kvName ? $kvName : '<REPLACE_ME>')",
    "",
    "# Storage",
    "AZURE_STORAGE_ACCOUNT=$($storageAccount ? $storageAccount : '<REPLACE_ME>')",
    "AZURE_STORAGE_CONTAINER=$($storageContainer ? $storageContainer : '<REPLACE_ME>')",
    "",
    "# Event Grid",
    "EVENTGRID_URI=$($eventGridUri ? $eventGridUri : '<REPLACE_ME>')",
    "EVENTGRID_KEY=$($eventGridKey ? $eventGridKey : '<REPLACE_ME>')",
    "",
    "# Application Insights",
    "APPINSIGHTS_INSTRUMENTATION_KEY=$($appInsightsKey ? $appInsightsKey : '<REPLACE_ME>')",
    "",
    "# Required secrets",
    "WEBHOOK_AUTH_SECRET=<REPLACE_ME>"
  ) -join "`n"

  Pop-Location
  Set-Content -Path $OutputFile -Value $content -Encoding UTF8
  Write-Host "Wrote $OutputFile"
} finally {
  if ((Get-Location).Path -eq (Resolve-Path $IaCDir).Path) {
    Pop-Location
  }
}
