param(
  [string]$IaCDir = "./iac/azure",
  [string]$OutputFile = "./.env.local.azure"
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path $IaCDir)) {
  Write-Error "IaC directory not found: $IaCDir"
  exit 1
}

Push-Location $IaCDir
try {
  $json = terraform output -json
  if (-not $json) {
    Write-Error "Terraform output is empty. Run 'terraform apply' first."
    exit 1
  }

  $outputs = $json | ConvertFrom-Json
  $kvUri = if ($outputs.key_vault_uri) { $outputs.key_vault_uri.value } else { $null }
  $eventGridUri = if ($outputs.eventgrid_topic_endpoint) { $outputs.eventgrid_topic_endpoint.value } else { $null }
  $eventGridKey = if ($outputs.eventgrid_topic_key) { $outputs.eventgrid_topic_key.value } else { $null }
  $appInsightsKey = if ($outputs.appinsights_instrumentation_key) { $outputs.appinsights_instrumentation_key.value } else { $null }

  $content = @(
    "# Generated by scripts/generate-azure-env.ps1",
    "# Do not commit this file",
    "",
    "AZURE_KEYVAULT_URL=$($kvUri ? $kvUri : '<REPLACE_ME>')",
    "",
    "# Event Grid",
    "EVENTGRID_URI=$($eventGridUri ? $eventGridUri : '<REPLACE_ME>')",
    "EVENTGRID_KEY=$($eventGridKey ? $eventGridKey : '<REPLACE_ME>')",
    "",
    "# Application Insights",
    "APPINSIGHTS_INSTRUMENTATION_KEY=$($appInsightsKey ? $appInsightsKey : '<REPLACE_ME>')",
    "",
    "# Required secrets",
    "WEBHOOK_AUTH_SECRET=<REPLACE_ME>",
    "GRAPH_TENANT_ID=<REPLACE_ME>",
    "GRAPH_CLIENT_ID=<REPLACE_ME>",
    "GRAPH_CLIENT_SECRET=<REPLACE_ME>",
    "ENTRA_GROUP_ID=<REPLACE_ME>"
  ) -join "`n"

  Pop-Location
  Set-Content -Path $OutputFile -Value $content -Encoding UTF8
  Write-Host "Wrote $OutputFile"
} finally {
  if ((Get-Location).Path -eq (Resolve-Path $IaCDir).Path) {
    Pop-Location
  }
}
