param(
  [string]$IaCDir = "./iac/aws",
  [string]$OutputFile = "./.env.local"
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path $IaCDir)) {
  Write-Error "IaC directory not found: $IaCDir"
  exit 1
}

Push-Location $IaCDir
try {
  $json = terraform output -json
  if (-not $json) {
    Write-Error "Terraform output is empty. Run 'terraform apply' first."
    exit 1
  }

  $outputs = $json | ConvertFrom-Json
  $apiUrl = $outputs.api_webhook_url.value
  $bucket = $outputs.s3_bucket_name.value
  $eventGridUri = if ($outputs.eventgrid_topic_endpoint) { $outputs.eventgrid_topic_endpoint.value } else { $null }
  $eventGridKey = if ($outputs.eventgrid_topic_key) { $outputs.eventgrid_topic_key.value } else { $null }

  if (-not $apiUrl -or -not $bucket) {
    Write-Error "Missing expected outputs. Ensure api_webhook_url and s3_bucket_name are defined."
    exit 1
  }

  $content = @(
    "# Generated by scripts/generate-aws-env.ps1",
    "# Do not commit this file",
    "",
    "AWS_WEBHOOK_ENDPOINT=$apiUrl",
    "AWS_S3_BUCKET=$bucket",
    "",
    "# Required secrets",
    "WEBHOOK_AUTH_SECRET=<REPLACE_ME>",
    "GRAPH_TENANT_ID=<REPLACE_ME>",
    "GRAPH_CLIENT_ID=<REPLACE_ME>",
    "GRAPH_CLIENT_SECRET=<REPLACE_ME>",
    "ENTRA_GROUP_ID=<REPLACE_ME>",
    "",
    "# Optional: Event Grid",
    "EVENTGRID_URI=$($eventGridUri ? $eventGridUri : '<REPLACE_ME>')",
    "EVENTGRID_KEY=$($eventGridKey ? $eventGridKey : '<REPLACE_ME>')"
  ) -join "`n"

  Pop-Location
  Set-Content -Path $OutputFile -Value $content -Encoding UTF8
  Write-Host "Wrote $OutputFile"
} finally {
  if ((Get-Location).Path -eq (Resolve-Path $IaCDir).Path) {
    Pop-Location
  }
}
