#!/usr/bin/env bash
set -euo pipefail

IAC_DIR="${1:-./iac/azure}"
OUTPUT_FILE="${2:-./.env.local.azure}"

if [ ! -d "$IAC_DIR" ]; then
  echo "IaC directory not found: $IAC_DIR" >&2
  exit 1
fi

pushd "$IAC_DIR" >/dev/null
JSON=$(terraform output -json || true)
if [ -z "$JSON" ]; then
  echo "Terraform output is empty. Run 'terraform apply' first." >&2
  exit 1
fi

KEYVAULT_URL=$(echo "$JSON" | python -c "import json,sys; o=json.load(sys.stdin); print(o.get('key_vault_uri', {}).get('value', ''))")
EVENTGRID_URI=$(echo "$JSON" | python -c "import json,sys; o=json.load(sys.stdin); print(o.get('eventgrid_topic_endpoint', {}).get('value', ''))")
EVENTGRID_KEY=$(echo "$JSON" | python -c "import json,sys; o=json.load(sys.stdin); print(o.get('eventgrid_topic_key', {}).get('value', ''))")
APPINSIGHTS_KEY=$(echo "$JSON" | python -c "import json,sys; o=json.load(sys.stdin); print(o.get('appinsights_instrumentation_key', {}).get('value', ''))")

popd >/dev/null

cat > "$OUTPUT_FILE" <<EOF
# Generated by scripts/generate-azure-env.sh
# Do not commit this file

AZURE_KEYVAULT_URL=${KEYVAULT_URL:-<REPLACE_ME>}

# Event Grid
EVENTGRID_URI=${EVENTGRID_URI:-<REPLACE_ME>}
EVENTGRID_KEY=${EVENTGRID_KEY:-<REPLACE_ME>}

# Application Insights
APPINSIGHTS_INSTRUMENTATION_KEY=${APPINSIGHTS_KEY:-<REPLACE_ME>}

# Required secrets
WEBHOOK_AUTH_SECRET=<REPLACE_ME>
GRAPH_TENANT_ID=<REPLACE_ME>
GRAPH_CLIENT_ID=<REPLACE_ME>
GRAPH_CLIENT_SECRET=<REPLACE_ME>
ENTRA_GROUP_ID=<REPLACE_ME>
EOF

echo "Wrote $OUTPUT_FILE"
