#!/usr/bin/env bash
set -euo pipefail

IAC_DIR="${1:-./iac/aws}"
OUTPUT_FILE="${2:-./.env.local}"

if [ ! -d "$IAC_DIR" ]; then
  echo "IaC directory not found: $IAC_DIR" >&2
  exit 1
fi

pushd "$IAC_DIR" >/dev/null
JSON=$(terraform output -json || true)
if [ -z "$JSON" ]; then
  echo "Terraform output is empty. Run 'terraform apply' first." >&2
  exit 1
fi

API_URL=$(echo "$JSON" | python -c "import json,sys; o=json.load(sys.stdin); print(o['api_webhook_url']['value'])")
BUCKET=$(echo "$JSON" | python -c "import json,sys; o=json.load(sys.stdin); print(o['s3_bucket_name']['value'])")
EVENTGRID_URI=$(echo "$JSON" | python -c "import json,sys; o=json.load(sys.stdin); print(o.get('eventgrid_topic_endpoint', {}).get('value', ''))")
EVENTGRID_KEY=$(echo "$JSON" | python -c "import json,sys; o=json.load(sys.stdin); print(o.get('eventgrid_topic_key', {}).get('value', ''))")

if [ -z "$API_URL" ] || [ -z "$BUCKET" ]; then
  echo "Missing expected outputs. Ensure api_webhook_url and s3_bucket_name are defined." >&2
  exit 1
fi

popd >/dev/null

cat > "$OUTPUT_FILE" <<EOF
# Generated by scripts/generate-aws-env.sh
# Do not commit this file

AWS_WEBHOOK_ENDPOINT=$API_URL
AWS_S3_BUCKET=$BUCKET

# Required secrets
WEBHOOK_AUTH_SECRET=<REPLACE_ME>
GRAPH_TENANT_ID=<REPLACE_ME>
GRAPH_CLIENT_ID=<REPLACE_ME>
GRAPH_CLIENT_SECRET=<REPLACE_ME>
ENTRA_GROUP_ID=<REPLACE_ME>

# Optional: Event Grid
EVENTGRID_URI=${EVENTGRID_URI:-<REPLACE_ME>}
EVENTGRID_KEY=${EVENTGRID_KEY:-<REPLACE_ME>}
EOF

echo "Wrote $OUTPUT_FILE"
