#!/usr/bin/env bash
# Sync Azure Terraform outputs to AWS terraform.tfvars
# Run after deploying Azure infrastructure

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AZURE_TF_DIR="$SCRIPT_DIR/../iac/azure"
AWS_TF_DIR="$SCRIPT_DIR/../iac/aws"
AWS_TFVARS_PATH="$AWS_TF_DIR/terraform.tfvars"

echo "================================================"
echo "Sync Azure -> AWS Terraform Variables"
echo "================================================"
echo ""

# Check directories
if [[ ! -d "$AZURE_TF_DIR" ]]; then
    echo "[ERROR] Azure Terraform directory not found: $AZURE_TF_DIR"
    exit 1
fi

if [[ ! -d "$AWS_TF_DIR" ]]; then
    echo "[ERROR] AWS Terraform directory not found: $AWS_TF_DIR"
    exit 1
fi

echo "[INFO] Getting Azure Terraform outputs..."
cd "$AZURE_TF_DIR"

# Get Azure outputs as JSON
if ! AZURE_OUTPUTS=$(terraform output -json 2>/dev/null); then
    echo "[ERROR] Failed to get Azure Terraform outputs. Deploy Azure infrastructure first."
    exit 1
fi

# Extract values using jq
TENANT_ID=$(echo "$AZURE_OUTPUTS" | jq -r '.tenant_id.value')
GRAPH_CLIENT_ID=$(echo "$AZURE_OUTPUTS" | jq -r '.app_client_id.value')
GRAPH_CLIENT_SECRET=$(echo "$AZURE_OUTPUTS" | jq -r '.app_client_secret.value')
BOT_APP_ID=$(echo "$AZURE_OUTPUTS" | jq -r '.bot_app_id.value')
BOT_APP_SECRET=$(echo "$AZURE_OUTPUTS" | jq -r '.bot_app_secret.value')
ADMIN_GROUP_ID=$(echo "$AZURE_OUTPUTS" | jq -r '.admin_group_id.value')
EVENTHUB_NAMESPACE=$(echo "$AZURE_OUTPUTS" | jq -r '.eventhub_namespace_name.value')
EVENTHUB_NAME=$(echo "$AZURE_OUTPUTS" | jq -r '.eventhub_name.value')
EVENTHUB_CONN_STRING=$(echo "$AZURE_OUTPUTS" | jq -r '.eventhub_connection_string.value')

echo "[OK] Retrieved Azure outputs"
echo "   Tenant ID: $TENANT_ID"
echo "   Graph Client ID: $GRAPH_CLIENT_ID"
echo "   Bot App ID: $BOT_APP_ID"
echo "   Admin Group ID: $ADMIN_GROUP_ID"
echo "   Event Hub Namespace: $EVENTHUB_NAMESPACE"
echo "   Event Hub Name: $EVENTHUB_NAME"
echo ""

cd "$SCRIPT_DIR"

# Read existing AWS tfvars if exists
declare -A EXISTING_VARS

if [[ -f "$AWS_TFVARS_PATH" ]]; then
    echo "[OK] Found existing terraform.tfvars"
    
    while IFS='=' read -r key value; do
        key=$(echo "$key" | xargs)
        value=$(echo "$value" | xargs | sed 's/^"//;s/"$//')
        if [[ -n "$key" && "$key" != \#* ]]; then
            EXISTING_VARS["$key"]="$value"
        fi
    done < "$AWS_TFVARS_PATH"
else
    echo "[WARN] No existing terraform.tfvars found, will create new"
fi

# Helper function to get existing or default value
get_var() {
    local key="$1"
    local default="${2:-}"
    echo "${EXISTING_VARS[$key]:-$default}"
}

# Generate terraform.tfvars
cat > "$AWS_TFVARS_PATH" <<EOF
# Auto-generated by sync-azure-to-aws.sh on $(date "+%Y-%m-%d %H:%M:%S")
# Azure values synced from Azure Terraform outputs

environment    = "$(get_var environment dev)"
aws_region     = "$(get_var aws_region us-east-1)"
aws_account_id = "$(get_var aws_account_id)"

# S3 bucket name (must be globally unique)
s3_bucket_name = "$(get_var s3_bucket_name tmf-webhook-payloads-dev)"

# Lambda package paths
lambda_package_path             = "$(get_var lambda_package_path "../../apps/aws-lambda/lambda.zip")"
authorizer_package_path         = "$(get_var authorizer_package_path "../../apps/aws-lambda-authorizer/authorizer.zip")"
eventhub_lambda_package_path    = "$(get_var eventhub_lambda_package_path "../../apps/aws-lambda-eventhub/lambda.zip")"

# Client state secret for webhook validation
client_state = "$(get_var client_state)"

# Optional: Email for SNS notifications
notification_email = "$(get_var notification_email)"

#=============================================================================
# AZURE-SYNCED VALUES (from Azure Terraform outputs)
#=============================================================================

# Microsoft Graph credentials
azure_graph_tenant_id     = "$TENANT_ID"
azure_graph_client_id     = "$GRAPH_CLIENT_ID"
azure_graph_client_secret = "$GRAPH_CLIENT_SECRET"

# Teams bot credentials
azure_bot_app_id     = "$BOT_APP_ID"
azure_bot_app_secret = "$BOT_APP_SECRET"

# Admin group for allow-listing
azure_allowed_group_id = "$ADMIN_GROUP_ID"

# Event Hub
eventhub_connection_string = "$EVENTHUB_CONN_STRING"
eventhub_name              = "$EVENTHUB_NAME"
eventhub_consumer_group    = "$(get_var eventhub_consumer_group '$Default')"

#=============================================================================
# AWS-SPECIFIC SETTINGS
#=============================================================================

# DynamoDB checkpoint table
eventhub_checkpoints_table_name = "$(get_var eventhub_checkpoints_table_name eventhub-checkpoints)"

# Subscription renewal schedule
renewal_schedule_expression = "$(get_var renewal_schedule_expression "cron(0 2 * * ? *)")"

# Event Hub polling
eventhub_poll_schedule_expression = "$(get_var eventhub_poll_schedule_expression "rate(1 minute)")"
eventhub_poll_window_minutes      = $(get_var eventhub_poll_window_minutes 10)
eventhub_max_events               = $(get_var eventhub_max_events 50)

# Meeting bot settings
group_cache_ttl_seconds = $(get_var group_cache_ttl_seconds 900)
teams_catalog_app_id    = "$(get_var teams_catalog_app_id)"
watched_user_ids        = "$(get_var watched_user_ids)"
poll_lookahead_minutes  = $(get_var poll_lookahead_minutes 60)

# Graph notifications
graph_notification_url          = "$(get_var graph_notification_url)"
graph_notification_client_state = "$(get_var graph_notification_client_state)"
EOF

echo "[OK] Written to: $AWS_TFVARS_PATH"

echo ""
echo "================================================"
echo "[DONE] Sync Complete!"
echo "================================================"
echo ""
echo "Next steps:"
echo "1. Review: $AWS_TFVARS_PATH"
echo "2. Fill in missing AWS values (aws_account_id, client_state, etc.)"
echo "3. cd iac/aws && terraform plan"
echo ""
